Remove dependency on usmap by updating bubble plotting and removing county_geo/state_geo
cmu-delphi/covidcast pull request #422
Opened 2021-01-17 16:21 UTC by sarah-colq

Update the bubble plots to use the shapefiles for state and county instead of usmap.   This also adds PR.  

Removes usmap as a dependency by removing state_geo and county_geo functions and documentation.  

Update dependency documentation.

2021-01-17 21:12 UTC, capnrefsmmat requested changes
Looking good. Just some style suggestions and minor improvements.

I think, though, we should file a follow-up issue to make `plot_choro` and `plot_bubble` share as much of the shapefile-loading and transformation code as possible. All the `is_alaska` checks and similar appear in several places, and there's enough duplication that `plot_choro` even loads the same state shapefile twice when plotting state data. We can probably simplify quite a bit.

(but that can wait until after we fix the package by merging this PR)

2021-01-17 21:12 UTC, capnrefsmmat commented on R-packages/covidcast/R/plot.R
> +  if (sum(map_df$back_color == missing_col) > 0) {
```suggestion
  if (any(map_df$back_color == missing_col)) {
```

2021-01-17 21:12 UTC, capnrefsmmat commented on R-packages/covidcast/R/data.R
> +"state_census"
newline at end of file

2021-01-17 21:12 UTC, capnrefsmmat commented on R-packages/covidcast/R/plot.R
> +  suppressWarnings({
Why is `suppressWarnings` needed here? Does `st_centroid` raise warnings? If it does, and we need to ignore them, we should have a comment saying what the warning is and why it's safe to ignore

2021-01-17 21:12 UTC, capnrefsmmat commented on R-packages/covidcast/R/plot.R
> +  geom_args$mapping = aes(geometry=geometry, size = bubble_val)
```suggestion
  geom_args$mapping = aes(geometry = geometry, size = bubble_val)
```

2021-01-17 21:12 UTC, capnrefsmmat commented on R-packages/covidcast/R/plot.R
> +  bubble_blank_if_all_na = function(geom_args, df){
```suggestion
  bubble_blank_if_all_na = function(geom_args, df) {
```

2021-01-17 21:12 UTC, capnrefsmmat commented on R-packages/covidcast/R/plot.R
> +    if(!all(is.na(df$bubble_val))){
```suggestion
    if (!all(is.na(df$bubble_val))) {
```

2021-01-17 21:12 UTC, capnrefsmmat commented on R-packages/covidcast/R/plot.R
> +    map_df = map_df %>% dplyr::filter(!(COUNTYFP == "000")) %>%
```suggestion
    map_df = map_df %>%
      dplyr::filter(!(COUNTYFP == "000")) %>%
```

2021-01-17 21:12 UTC, capnrefsmmat commented on R-packages/covidcast/R/plot.R
> +  # Explicitly drop zeros (and from levels) unless were asked not to
```suggestion
  # Explicitly drop zeros (and from levels) unless we're asked not to
```

2021-01-18 00:15 UTC, sarah-colq commented on R-packages/covidcast/R/plot.R
> +  suppressWarnings({
Is this sufficient?  This knowledge is based on stack overflow answers and a visual inspection of the bubbles.

2021-01-18 00:16 UTC, sarah-colq commented
I agree with filing a follow up issue.  I didn't want to take on too much with this PR and break everything since the dependency on usmap should be removed as soon as possible.  I'll file one.

2021-01-18 01:28 UTC, capnrefsmmat commented on R-packages/covidcast/R/plot.R
> +  suppressWarnings({
I think the new comment is sufficient, yeah. Even if the warning is right and the centroids aren't exact, we don't really need them to be perfectly precise

2021-01-18 01:33 UTC, capnrefsmmat approved these changes
Looks good, thanks

2021-01-18 01:33 UTC, merged