Update plotting function signatures
cmu-delphi/covidcast pull request #481
Opened 2021-03-08 03:55 UTC by sarah-colq

Make them more consistent.  Order of prediction_cards (or df), facet_rows, facet_cols, legend_position, grp_vars, avg_vars, geo_type, type, and then custom arguments.  df is kept for plot_canonical because that function is so general; all other functions use prediction_cards.

2021-03-08 18:27 UTC, dajmcdon approved these changes
This looks mostly fine to me. @JedGrabman can you give it a quick look to ensure that merging won't break anything in the evaluation notebook?

2021-03-08 20:01 UTC, JedGrabman requested changes

2021-03-08 21:24 UTC, sarah-colq commented on R-packages/evalcast/R/plot_canonical.R
> +                           grp_vars = "forecaster",
Oops thanks for catching fixed.

2021-03-08 21:25 UTC, sarah-colq commented
@JedGrabman @dajmcdon fixed issues Jed pointed out, should be good to go.

2021-03-09 15:57 UTC, JedGrabman approved these changes

2021-03-09 17:30 UTC, merged