Set up plot testing infrastructure and tests for plot_coverage
cmu-delphi/covidcast pull request #517
Opened 2021-03-30 19:47 UTC by sarah-colq

a) set up DEVELOP.md and subdirectories for using vdiffr to test plots.
b) Add tests for plot_coverage (not one type, see issue #516)
c) move compute_coverage and compute_calibration to their plot files because that's the only place those functions are used (to emulate how plot_width) is set up. 
d) move test_legal_faceting and Interaction(...) to grp_processing_for_facets.R since those are used by multiple plots.
e) rename test-evaluate to test-evaluate_predictions because the main file was renamed as well.

2021-03-31 22:03 UTC, dajmcdon requested changes

2021-03-31 22:03 UTC, dajmcdon commented on R-packages/evalcast/DEVELOP.md
> +## Documentation
This is great!!!

2021-03-31 22:03 UTC, dajmcdon commented on R-packages/evalcast/tests/testthat/test-grp_processing.R
> +})
Need a trailing new line here.

2021-03-31 22:03 UTC, dajmcdon commented on R-packages/evalcast/tests/testthat/test-plot_coverage.R
> +library(testthat)
shouldn't need `library(testthat)` I don't think.

2021-03-31 22:05 UTC, dajmcdon commented on R-packages/evalcast/DEVELOP.md
> +## Documentation
Comment applies to the entire file!

2021-04-05 18:58 UTC, sarah-colq commented on R-packages/evalcast/DESCRIPTION
> +    vdiffr
Already in the suggests!

2021-04-05 18:58 UTC, sarah-colq commented on R-packages/evalcast/DEVELOP.md
> +## Documentation
Thanks :D

2021-04-05 19:37 UTC, merged